### PR TITLE
Added pagination to all routes

### PR DESCRIPTION
**Pull request by MuminAhmadKhan**
Pagination was added to all routes. By default there is no pagination.
page & limit(number of item per page) are the two query parameters.

### CODE REVIEW

**Review by TAKANOME-DEV — APPROVED** [review]
LGTM

**Comment by MuminAhmadKhan** [comment]
@MizouziE Is it OK ?

**Review by MizouziE — APPROVED** [review]
Amazing stuff! Thank you very much!

**Comment by MuminAhmadKhan** [comment]
@MizouziE  Thanks

**Pull request merged**
