### PR TITLE
Test: add jest & supertest

### PR DESCRIPTION
**Pull request by takanome-dev**
I do a little bit of refactoring:
- move all the code in a `src` folder.
- create a `utils` containing these two files:
  - `getTitle.js`: this function filter the title, It was created in #45
  - `getDataFromCheerio.js`: I created this function to remove code duplication and clean up the code. You can have a look in  filed changes tab ;
- I added a `server.js` file that export our app. The reason is that we have to pass the app to `supertest`  so that it can make http request
- There is a `jest.config.js` file which hold some basic config, you can learn more about them [here](https://jestjs.io/docs/configuration)
- `__mocks__`: this is our mock response, I added `axios.js` file which is a fake axios method. Every request to axios will return the data in our mock file
- `__tests__` this is our tests, it only contain a small test to make sure we are getting all the articles.

Let me know if you have any question 💯

### CODE REVIEW

**Comment by TAKANOME-DEV** [comment]
You can install [Gitpod](https://chrome.google.com/webstore/detail/gitpod-always-ready-to-co/dodmmooeoklaejobgleioelladacbeki) to quickly review the changes inside vscode in your browser

**Comment by MizouziE** [comment]
Thanks @TAKANOME-DEV !
I'll go thru it all and merge ASAP 👍
You the man!

**Review by MizouziE — APPROVED** [review]
Wow man! That's a serious job you've done there 🤯
I just hope we can keep the documentation up to scratch now! 

I really really appreciate all the work you're putting in to this, every day this project is exceeding my expectations by miles 🙏

I'm looking forward to jumping back into this properly myself just to try out writing some tests!

**Comment by TAKANOME-DEV** [comment]
Don't worry about it, I love doing these stuff 😃 
Yeah, you should definitively give it a shot

**Pull request merged**
