### PR TITLE
fix : restricted node version to version mentioned in package.json #169

### PR DESCRIPTION
**Pull request by sanyamgandhak**
## What type of PR is this? (check all applicable)

- [ ] 💡 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [ ] ✅ Test

## Description

This PR restrict the node version to the version specified in the package.json . user is force to have that version installed for build to happen

## Fixes issue :  #169

Screenshot (889)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by TAKANOME-DEV** [comment]
@sanyamgandhak please add a description and link the issue number

**Review by MizouziE — CHANGES_REQUESTED** [review]
Please remove package-lock.json from the PR. 

Good to see that the addition of the strict-engine file is having the desired effect though! 👍👍

**Comment by sanyamgandhak** [comment]
> @sanyamgandhak please add a description and link the issue number (example: Fixes #123534) in the `Fixes Issue` section ⬆️

Done !!

**Comment by sanyamgandhak** [comment]
> Please remove package-lock.json from the PR.
> 
> Good to see that the addition of the strict-engine file is having the desired effect though! 👍👍

Do I need to make same changes as in package.lock.json and then push the repo ?

**Review by MizouziE — COMMENTED** [review]
Hi @sanyamgandhak , deleting the file was not what I meant, I apologise for not being clear. I meant to revert that commit in which it was added, then to submit only changes to the new file. I will give clearer details back in the comments of the original issue and close this PR as it technically is possible to save, but it is much more simple to just start from scratch.

**Pull request closed without merging**
