### PR TITLE
[chore] remove the .vscode folder

### LINKED ISSUE #189: Chore: Remove an unwanted directory
### What work needs to be performed?

Please remove the directory `./.vscode` along with all it's contents.

After removing, please `git add .vscode` and then `git commit -m "<suitable commit message>"` and then push your changes to create a new PR.

As the folder is already included in `.gitignore` you will not need to do anything here.

### Additional information

The easiest way to do this would be via command line in the root directory:
```bash
rm -r .vscode
```

This will delete the folder with all contents in one go. Sorted.

### PR DESCRIPTION
**Pull request by pedes**
## What type of PR is this? (check all applicable)

- [ ] 💡 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [x] (Others) Chore

## Description

This PR removes the unnecessary .vscode folder.

## Fixes issue

Fixes #189 

## Screenshots (if appropriate)

N/A

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by pedes** [comment]
All yours @MizouziE , thanks.

**Review by TAKANOME-DEV — APPROVED** [review]
Thanks for contributing :+1:

**Comment by TAKANOME-DEV** [comment]
@MizouziE , the `first-interaction` action did not run, that's weird :thinking:

**Comment by MizouziE** [comment]
> @MizouziE , the `first-interaction` action did not run, that's weird :thinking:

I didn't think it would tbh, but wanted to give it a chance first. I need to set up something on the repo itself. So I'll look into it properly now.

**Review by MizouziE — APPROVED** [review]

**Comment by MizouziE** [comment]
Perfect, thank you!

@all-contributors please add @pedes for maintenance

**Comment by MizouziE** [comment]
FYI @TAKANOME-DEV it did run, but possibly didn't count as a first contribution as a comment had been made previously??

I'll have to read up some more...

image

**Pull request merged**
